name: Deploy to server
on:
  push:
    branches: [main]
jobs:

  tests_frontend:
    name: Build and run frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Installing depedencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Set env vars
        run: printf "WS_API_URL=${{ secrets.WS_API_URL }}\nREST_API_URL=${{ secrets.REST_API_URL }}" > .env
      - name: Build the app
        run: npm run build
      - name: Start the server
        run: npm start & wait-on http://localhost:5000
      - name: Run integration tests
        run: npm run cy:run

  deploy_svelte:
    needs: tests_frontend
    name: Deploy frontend app
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: | 
          source ~/.nvm/nvm.sh
          cd undercover/
          nvm use
          pm2 stop svelte
          git fetch
          git reset --hard HEAD
          git merge '@{u}'
          printf "WS_API_URL=${{ secrets.WS_API_URL }}\nREST_API_URL=${{ secrets.REST_API_URL }}" > .env
          npm install
          npm run build
          pm2 restart svelte